name: Terraform Quality Checks

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev, stage, prod)"
        required: true
        default: "dev"
  # pull_request:
  #   branches:
  #     - main
  #     - dev
  #     - stage
  #     - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tool: [fmt, validate, tflint, tfsec, checkov]

    env:
      TF_WORKING_DIR: azure-terraform/aks-centralus-${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
                  
      # Terraform FMT (check only)
      - name: Terraform Fmt
        if: matrix.tool == 'fmt'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      # 2. Terraform Validate
      - name: Terraform Init
        if: matrix.tool == 'validate'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend=false

      - name: Terraform Validate
        if: matrix.tool == 'validate'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # 3. TFLint
      - name: Install tflint
        if: matrix.tool == 'tflint'
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        if: matrix.tool == 'tflint'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tflint --recursive

        # 4. TFSEC
      - name: Install tfsec
        if: matrix.tool == 'tfsec'
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash

      - name: Run tfsec
        if: matrix.tool == 'tfsec'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tfsec .

      # 5. Checkov
      - name: Install Checkov
        if: matrix.tool == 'checkov'
        run: pip install checkov

      - name: Run Checkov
        if: matrix.tool == 'checkov'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: checkov -d .